### ISSUE TITLE
Exception: Contract deployment failed in Linux

### ISSUE THREAD

**Issue by jistro** [runtimeverification/simbolik-vscode#28]
# Environment
Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.9.3-76060903-generic

# How to reproduce

1)  install and set up simbolik
2) debug a function 
3) bug appears 

# debug console 

```
Welcome to Simbolik! Happy debugging! 

Do you have questions, or need help?

Visit our Documentation: https://docs.runtimeverification.com/simbolik 
Join our Discord: https://discord.gg/jnvEeDxW
Join our TG group: https://t.me/rv_simbolik

Found a bug or have a feature request?

Please report it here: https://github.com/runtimeverification/simbolik-vscode/issues

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/simbolik/adapter.py", line 317, in launch_request
    trace = await driver.execute(config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/simbolik/backend/rpc/backend.py", line 65, in execute
    return await self.launch(config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/simbolik/backend/rpc/backend.py", line 89, in launch
    address, init_code = self._deploy_contract(web3, config.build_info, str(config.file), config.contract_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/simbolik/backend/rpc/backend.py", line 156, in _deploy_contract
    raise Exception('Contract deployment failed')
Exception: Contract deployment failed
```

**Comment by RaoulSchaffranek** [comment]
Hi @jistro,
Thanks for reporting the issue. Can you share the code or a minimal example to reproduce the bug?
